### ISSUE TITLE
Persistent "Wrong Password" when uploading

### ISSUE THREAD

**Issue by charles-spurgeon** [jackyes/GoTube#1]
I get a persistent "Wrong password" from the web UI when uploading content using the stock config.yaml and a customized version.

This also happens when I set _AllowUploadWithPsw_ True and use the password I set in config.yaml

The app is great and suits a specific need I have, so I'd love to figure it out.  Thanks!

**Comment by jackyes** [comment]
Hi, the default password is "GoTube".

You can change it  generating a bcrypt password hash and insert as password in the config.yaml.
`mkpasswd -m bcrypt -R 10 <yourpassword>`

Example:
`mkpasswd -m bcrypt -R 10 my_new_password`
result:
$2b$10$Nxrb7Yz699QcINCpXejLTu2ksUCmLNPFv.sbJhTSL1fPgQ6yT.ls.`

then change the `Psw: ` in config yaml.  
`Psw:  $2b$10$Nxrb7Yz699QcINCpXejLTu2ksUCmLNPFv.sbJhTSL1fPgQ6yT.ls.`

Now (after an app restart) you can upload video using password "my_new_password"

I hope this can help you. If you want to tell us more about your use case and feel free to propose ideas and improvements ;)

**Comment by TheMrChao** [comment]
Awesome--that makes sense, I did use the command but I missed how to use it.

How would I use with _AllowUploadWithPsw_ set to false?  I hadn't seen a way for the client to store a password?

I'd like to privately host some training videos for some coaches that work with my kids.  It would be great to have 4K support if possible, maybe even a way to bypass transcoding if I'm preparing media in final form.

This is one of the only drop-in containers I've seen that can do what you're doing so I'm really excited to see where the development takes the product!

Thanks!!!

**Comment by jackyes** [comment]
If "AllowUploadWithPsw" is set to false, no password is required to upload videos.

The video is converted into 3 resolutions to avoid slowdowns during playback.
To have the video in 720p, 1080p, and 4k, modify the following in the config file:
`VideoResLow`: to 720
`VideoResMed`: to 1080
`VideoResHigh`: to 2160
  
The bitrate can also be increased using the appropriate entries in the config file using the same logic (adjust to you needs).
`BitRateLow: 1500k  #BitRate value used in low conversion`  
`BitRateMed: 3000k  #BitRate value used in medium conversion`  
`BitRateHigh: 6000k #BitRate value used in high conversion`  
  
Consider increasing `NrOfCoreVideoConv` by entering the number of processor cores to speed up transcoding.  
Additionally, you can include only the video on other HTML pages on other sites or domains (copy the code by clicking on the "embed" button that is generated when you watch a video).

**Comment by charles-spurgeon** [comment]
Thanks!

I've set the flag to false and redeployed the container, cleared browser cache, etc., and the error I now get is "permission denied".

<img width="1708" alt="Screenshot 2023-03-13 at 11 58 01 AM" src="https://user-images.githubusercontent.com/50151429/224758361-315df9d2-b771-47f2-bfad-93fa22f78016.png">

**Comment by charles-spurgeon** [comment]
Thanks!

(I deleted my previous comment, I figured out the issue right after I posted it. 🤣)

**Comment by charles-spurgeon** [comment]
Regarding the conversion prefs... could any of those be moved into an "admin" panel?

**Comment by jackyes** [comment]
These are settings that, if modified, only have an effect on subsequent conversions and are theoretically not changed often. However, creating an admin panel for these settings and also for deleting videos (currently, you have to manually delete the <VideoName> folder inside ./conversion/) is a great idea!

**Comment by jackyes** [comment]
The implementation of the Admin Panel and password for video uploads is going well :) The update will probably be published today or tomorrow.
Delete Page Will come on futher updates
